package musicPlayer.model;

public enum Genre {
	POP, INDUSTRIAL_METAL, HEAVY_METAL, DEATH_METAL, ALTERNATIVE_METAL, JAZZ, REGGAE, HIP_HOP, TECHNO, DISCO, HOUSE, BLUES, RAP, PUNK_ROCK, RYTHM_AND_BLUES, FOLK, DUBSTEP, ELECTRO, FUNK, COUNTRY, MELODY, ORCHESTRA, CLASSICAL, INSTRUMENTAL, DRUM_AND_BASS, TRANCE, GOSPEL, OPERA, NEW_WAVE, POP_ROCK, BLUEGRASS, PROGRESSIVE_ROCK, FOLK_ROCK, SOUL, HARDCORE_PUNK, SKA, INDIE_POP, TRAP, WORLD, REGGAETON, BLUES_ROCK
}
